[versions]
lwjglVersion = "3.4.2"
jomlVersion = "1.10.9"
jomlPrimitivesVersion = "1.11.1"
log4j = "2.26.1"
log4j-api-kotlin = "1.5.0"
jackson-databind = "2.19.2"
kotlinx-serialization-json = "1.11.0"

[libraries]
lwjgl = { group = "org.lwjgl", name = "lwjgl", version.ref = "lwjglVersion" }
lwjgl-assimp = { group = "org.lwjgl", name = "lwjgl-assimp", version.ref = "lwjglVersion" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw", version.ref = "lwjglVersion" }
lwjgl-openal = { group = "org.lwjgl", name = "lwjgl-openal", version.ref = "lwjglVersion" }
lwjgl-opengl = { group = "org.lwjgl", name = "lwjgl-opengl", version.ref = "lwjglVersion" }
lwjgl-stb = { group = "org.lwjgl", name = "lwjgl-stb", version.ref = "lwjglVersion" }
lwjgl-sdl = { group = "org.lwjgl", name = "lwjgl-sdl", version.ref = "lwjglVersion" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

joml = { group = "org.joml", name = "joml", version.ref = "jomlVersion" }
joml-primitives = { group = "org.allaymc", name = "joml-primitives", version.ref = "jomlPrimitivesVersion" }

log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-api-kotlin = { group = "org.apache.logging.log4j", name = "log4j-api-kotlin", version.ref = "log4j-api-kotlin" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }

[bundles]
lwjgl = ["lwjgl", "lwjgl-assimp", "lwjgl-glfw", "lwjgl-openal", "lwjgl-opengl", "lwjgl-stb", "lwjgl-sdl"]
log4j = ["log4j-api", "log4j-core", "log4j-api-kotlin"]
joml = ["joml", "joml-primitives"]